# Generated by Django 2.2.1 on 2022-03-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_parsing', '0002_tokenreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='email_send',
            field=models.BooleanField(blank=True, default='False', null=True, verbose_name='Уведомлять об изменении цены'),
        ),
    ]
