# Generated by Django 2.2.1 on 2022-03-19 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_parsing', '0003_auto_20220318_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analoglink',
            name='analog_name',
            field=models.CharField(max_length=10000, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='grouplink',
            name='group_name',
            field=models.CharField(max_length=10000, verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(max_length=10000, verbose_name='Название товара'),
        ),
    ]
