# Generated by Django 2.2.1 on 2022-03-13 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=10000, verbose_name='Ссылка')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к ссылке')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_link', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='PriceLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=10000, verbose_name='Цена')),
                ('data_parser_price', models.DateTimeField(auto_now_add=True, verbose_name='Дата парсинга цены')),
                ('price_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_link', to='market_parsing.Link')),
            ],
        ),
    ]
