# Generated by Django 2.2.1 on 2022-03-19 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market_parsing', '0003_link_email_send'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalogLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=10000, verbose_name='Ссылка')),
                ('analog_name', models.CharField(max_length=10000, verbose_name='Название товара')),
            ],
        ),
        migrations.RemoveField(
            model_name='link',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='link',
            name='email_send',
        ),
        migrations.AddField(
            model_name='link',
            name='name',
            field=models.CharField(default='', max_length=10000, verbose_name='Название товара'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='link',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_link', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь ссылки'),
        ),
        migrations.CreateModel(
            name='GroupLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=10000, verbose_name='Название группы')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_group', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь группы')),
            ],
        ),
        migrations.CreateModel(
            name='AnalogLinkPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analog_price', models.CharField(max_length=10000, verbose_name='Цена')),
                ('analog_data_parser_price', models.DateTimeField(auto_now_add=True, verbose_name='Дата парсинга цены')),
                ('analog_link_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analog_link_price', to='market_parsing.AnalogLink')),
            ],
        ),
        migrations.AddField(
            model_name='analoglink',
            name='analog_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analog_link', to='market_parsing.Link'),
        ),
        migrations.AddField(
            model_name='analoglink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_analog_link', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь аналоговой ссылки'),
        ),
        migrations.AddField(
            model_name='link',
            name='group_link',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_link', to='market_parsing.GroupLink', verbose_name='Группа'),
            preserve_default=False,
        ),
    ]
